* Gitter client for Emacs

[[https://gitter.im/M-x-Gitter/Lobby][https://badges.gitter.im/M-x-Gitter/Lobby.svg]]

** Status

Work in process, though it is possible to view real-time messages in rooms and send message.

** Prerequisites

- cURL
- Emacs 24.1
- (*Optional*) If you want to display Emoji, install [[https://github.com/iqbalansari/emacs-emojify][emojify]] *or* [[https://github.com/syl20bnr/emacs-emoji-cheat-sheet-plus][emoji-cheat-sheet-plus]] *or* [[https://github.com/dunn/company-emoji][company-emoji]], they are all avaiable from MELPA. You only need to install one of them, but if you install more than one of them, the priority is emojify > emoji-cheat-sheet-plus > company-emoji.

** Setup

Add gitter.el to your ~load-path~ and require. Something like:

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "path/to/gitter.el/")
  (require 'gitter)
#+END_SRC

Alternatively, if you manage loading packages with use-package:

#+BEGIN_SRC emacs-lisp
  (use-package gitter
    :load-path "path/to/gitter.el/"
    :defer t
    :commands gitter)
#+END_SRC

Then you will need to set the authentication-token. Follow these steps to get your token:
1) Visit URL `https://developer.gitter.im'
2) Click Sign in (top right)
3) You will see your personal access token at
   URL `https://developer.gitter.im/apps'

When you save this variable, DON'T WRITE IT ANYWHERE PUBLIC.

#+BEGIN_SRC emacs-lisp
  (setq gitter-token "your-token")
#+END_SRC

** Usage

Type ~M-x gitter~ to join a romm and start chatting.
