#+TITLE: gitter.el
#+AUTHOR: Chunyang Xu

[[https://melpa.org/#/gitter][https://melpa.org/packages/gitter-badge.svg]]
[[https://travis-ci.org/xuchunyang/gitter.el][https://travis-ci.org/xuchunyang/gitter.el.svg?branch=master]]
[[https://gitter.im/M-x-Gitter/Lobby][https://badges.gitter.im/M-x-Gitter/Lobby.svg]]

A [[https://gitter.im/][Gitter]] client for [[https://www.gnu.org/software/emacs/][GNU Emacs]].

* Prerequisites

- cURL
- Emacs 24.1 or newer

* Install

** Melpa

~gitter.el~ is available from
Melpa. After[[https://melpa.org/#/getting-started][setting up]] Melpa
as a repository and update the local package list, you can install
~gitter.el~ and its dependencies using ~M-x package-install gitter~.

** Manually

Add gitter.el to your ~load-path~ and require. Something like:

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "path/to/gitter.el/")
  (require 'gitter)
#+END_SRC

If you want to avoid loading ~gitter.el~ at Emacs startup, autoload
the ~gitter~ command instead of requiring.

* Setup

You need to set ~gitter-token~ to the authentication-token. Follow these steps to get your token:
1) Visit URL `https://developer.gitter.im'
2) Click Sign in (top right)
3) You will see your personal access token at
   URL `https://developer.gitter.im/apps'

When you save this variable, DON'T WRITE IT ANYWHERE PUBLIC.

#+BEGIN_SRC emacs-lisp
  (setq gitter-token "your-token")
#+END_SRC

* Usage

Type ~M-x gitter~ to join a room and start chatting.

* Limitation

If you are a serious Gitter user (I am not) and you compare this
little program with other official Gitter clients, I guess you will
probably be very disappointed: lack of functions and features, buggy
etc, so now you have been warned. However, feedback, suggestion and
patch are always welcome.

By the way, Gitter provides [[https://irc.gitter.im/][IRC access]] and there are several
well-known IRC clients for Emacs.

* To do

- [ ] Markup message
  - plain link
  - Markdown link
  - Github-flavored Markdown image
  - @mention
  - Github #issue
  - Markdown inline code block (add syntax highlighting if it is
    possible and very easy)
  - Github-flavored fenced code block (add syntax highlighting if it
    has proper language tag)
  - Github-flavored indented with four spaces code block (prefer no
    syntax highlighting to avoiding guessing what language the code is
    in, I don't like guess)
  - etc
