#+TITLE: gitter.el
#+AUTHOR: Chunyang Xu

[[https://gitter.im/M-x-Gitter/Lobby][https://badges.gitter.im/M-x-Gitter/Lobby.svg]]

A rough [[https://gitter.zendesk.com/hc/en-us/articles/200178981-What-s-Gitter-written-in-][Gitter]] client for [[https://www.gnu.org/software/emacs/][GNU Emacs]].

* Prerequisites

- cURL
- Emacs 24.1 or newer

* Setup

Add gitter.el to your ~load-path~ and require. Something like:

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "path/to/gitter.el/")
  (require 'gitter)
#+END_SRC

Alternatively, if you manage loading packages with use-package:

#+BEGIN_SRC emacs-lisp
  (use-package gitter
    :load-path "path/to/gitter.el/"
    :defer t
    :commands gitter)
#+END_SRC

Then you will need to set the authentication-token. Follow these steps
to get your token:
1) Visit URL `https://developer.gitter.im'
2) Click Sign in (top right)
3) You will see your personal access token at
   URL `https://developer.gitter.im/apps'

When you save this variable, DON'T WRITE IT ANYWHERE PUBLIC.

#+BEGIN_SRC emacs-lisp
  (setq gitter-token "your-token")
#+END_SRC

* Usage

Type ~M-x gitter~ to join a room and start chatting.

* Customization

** Emoji

If you want to display Emoji, install [[https://github.com/iqbalansari/emacs-emojify][emojify]] *or*
[[https://github.com/syl20bnr/emacs-emoji-cheat-sheet-plus][emoji-cheat-sheet-plus]] *or* [[https://github.com/dunn/company-emoji][company-emoji]], they are all available from
MELPA. You only need to install one of them, but if you install more
than one of them, the priority is emojify > emoji-cheat-sheet-plus >
company-emoji.

* Limitation

If you are a serious Gitter user (I am not) and you compare this
little program with other official Gitter clients, I guess you will
probably be very disappointed: lack of functions and features, buggy
etc, so now you have been warned. However, feedback, suggestion and
patch are always welcome.

By the way, Gitter provides [[https://irc.gitter.im/][IRC access]] and there are several
well-known IRC clients for Emacs.

* To do

- [ ] Markup message
  - plain link
  - Markdown link
  - Github-flavored Markdown image
  - @mention
  - Github #issue
  - Markdown inline code block (add syntax highlighting if it is
    possible and very easy)
  - Github-flavored fenced code block (add syntax highlighting if it
    has proper language tag)
  - Github-flavored indented with four spaces code block (prefer no
    syntax highlighting to avoiding guessing what language the code is
    in, I don't like guess)
  - etc
